config/routes.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

Diaspora::Application.routes.draw do


  # Posting and Reading

  resources :reshares

  resources :aspects do
    put :toggle_contact_visibility
  end

  resources :status_messages, :only => [:new, :create]

  resources :posts, :only => [:show, :destroy] do
    resources :likes, :only => [:create, :destroy, :index]
    resources :comments, :only => [:new, :create, :destroy, :index]
  end
  get 'p/:id' => 'posts#show', :as => 'short_post'
  get 'public_stream' => 'posts#index', :as => 'public_stream'
  # roll up likes into a nested resource above
  resources :comments, :only => [:create, :destroy] do
    resources :likes, :only => [:create, :destroy, :index]
  end


  get 'bookmarklet' => 'status_messages#bookmarklet'

  resources :photos, :except => [:index] do
    put :make_profile_photo
  end

  # ActivityStreams routes
  scope "/activity_streams", :module => "activity_streams", :as => "activity_streams" do
    resources :photos, :controller => "photos", :only => [:create]
  end

  resources :conversations do
    resources :messages, :only => [:create, :show]
    delete 'visibility' => 'conversation_visibilities#destroy'
  end

  resources :notifications, :only => [:index, :update] do
    get :read_all, :on => :collection
  end

  resources :tags, :only => [:index]
  scope "tags/:name" do
    post   "tag_followings" => "tag_followings#create", :as => 'tag_tag_followings'
    delete "tag_followings" => "tag_followings#destroy"
  end

  post   "multiple_tag_followings" => "tag_followings#create_multiple", :as => 'multiple_tag_followings'

  get "tag_followings" => "tag_followings#index", :as => 'tag_followings'
  resources :mentions, :only => [:index]
  resources "tag_followings", :only => [:create]

  get 'comment_stream' => 'comment_stream#index', :as => 'comment_stream'

  get 'like_stream' => 'like_stream#index', :as => 'like_stream'

  get 'tags/:name' => 'tags#show', :as => 'tag'

  resources :apps, :only => [:show]

  #Cubbies info page
  resource :token, :only => :show


  # Users and people

  resource :user, :only => [:edit, :update, :destroy], :shallow => true do
    get :getting_started_completed
    get :export
    get :export_photos
  end

  controller :users do
    get 'public/:username'          => :public,           :as => 'users_public'
    match 'getting_started'         => :getting_started,  :as => 'getting_started'
    match 'privacy'                 => :privacy_settings, :as => 'privacy_settings'
    get 'getting_started_completed' => :getting_started_completed
    get 'confirm_email/:token'      => :confirm_email,    :as => 'confirm_email'
  end

  # This is a hack to overide a route created by devise.
  # I couldn't find anything in devise to skip that route, see Bug #961
  match 'users/edit' => redirect('/user/edit')

  devise_for :users, :controllers => {:registrations => "registrations",
                                      :password      => "devise/passwords",
                                      :sessions      => "sessions",
                                      :invitations   => "invitations"} do
    get 'invitations/resend/:id' => 'invitations#resend', :as => 'invitation_resend'
    get 'invitations/email' => 'invitations#email', :as => 'invite_email'
  end

  get 'login' => redirect('/users/sign_in')

  scope 'admins', :controller => :admins do
    match :user_search
    get   :admin_inviter
    get   :weekly_user_stats
    get   :correlations
    get   :stats, :as => 'pod_stats'
  end

  resource :profile, :only => [:edit, :update]

  resources :contacts,           :except => [:update, :create] do
    get :sharing, :on => :collection
  end
  resources :aspect_memberships, :only  => [:destroy, :create, :update]
  resources :share_visibilities,  :only => [:update]
  resources :blocks, :only => [:create, :destroy]

  get 'spotlight' => 'community_spotlight#index', :as => 'spotlight'

  get 'community_spotlight' => "contacts#spotlight", :as => 'community_spotlight'

  get 'stream' => "multis#index", :as => 'multi'

  resources :people, :except => [:edit, :update] do
    resources :status_messages
    resources :photos
    get  :contacts
    get "aspect_membership_button" => :aspect_membership_dropdown, :as => "aspect_membership_button"
    collection do
      post 'by_handle' => :retrieve_remote, :as => 'person_by_handle'
      get :tag_index
    end
  end
  get '/u/:username' => 'people#show', :as => 'user_profile'
  get '/u/:username/profile_photo' => 'users#user_photo'
  # Federation

  controller :publics do
    get 'webfinger'             => :webfinger
    get 'hcard/users/:guid'     => :hcard
    get '.well-known/host-meta' => :host_meta
    post 'receive/users/:guid'  => :receive
    post 'receive/public'       => :receive_public
    get 'hub'                   => :hub
  end



  # External

  resources :authorizations, :only => [:index, :destroy]
  scope "/oauth", :controller => :authorizations, :as => "oauth" do
    get "authorize" => :new
    post "authorize" => :create
    post :token
  end

  resources :services, :only => [:index, :destroy]
  controller :services do
    scope "/auth", :as => "auth" do
      match ':provider/callback' => :create
      match :failure
    end
    scope 'services' do
      match 'inviter/:provider' => :inviter, :as => 'service_inviter'
      match 'finder/:provider'  => :finder,  :as => 'friend_finder'
    end
  end

  scope 'api/v0', :controller => :apis do
    get :me
  end

  namespace :api do
    namespace :v0 do
      get "/users/:username" => 'users#show', :as => 'user'
      get "/tags/:name" => 'tags#show', :as => 'tag'
    end
  end


  # Mobile site

  get 'mobile/toggle', :to => 'home#toggle_mobile', :as => 'toggle_mobile'

  #Protocol Url
  get 'protocol' => redirect("https://github.com/diaspora/diaspora/wiki/Diaspora%27s-federation-protocol")

  # Resque web
  if AppConfig[:mount_resque_web]
    mount Resque::Server.new, :at => '/resque-jobs', :as => "resque_web"
  end

  # Logout Page (go mobile)
  get 'logged_out' => 'users#logged_out', :as => 'logged_out'

  # Startpage
  root :to => 'home#show'
end

app/models/acts_as_taggable_on/tag.rb
class ActsAsTaggableOn::Tag

  def followed_count
   @followed_count ||= TagFollowing.where(:tag_id => self.id).count
  end

  def self.tag_text_regexp
    @@tag_text_regexp ||= (RUBY_VERSION.include?('1.9') ? "[[:alnum:]]_-" : "\\w-")
  end

  def self.autocomplete(name)
    where("name LIKE ?", "#{name.downcase}%")
  end

  def self.normalize(name)
    if name =~ /^#?<3/
      # Special case for love, because the world needs more love.
      '<3'
    elsif name
      name.gsub(/[^#{self.tag_text_regexp}]/, '').downcase
    end
  end
end

app/models/api/v0/serializers/tag.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class Api::V0::Serializers::Tag

  def initialize(tag)
    @stream = Stream::Tag.new(nil, tag)
  end

  def as_json(opts={})
    {
      "name" => @stream.tag_name,
      "person_count" => @stream.tagged_people_count,
      "followed_count" => @stream.tag_follow_count,
      "posts" => []
    }
  end
end

app/controllers/api/v0/tags_controller.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class Api::V0::TagsController < ApplicationController
  def show
    render :json => Api::V0::Serializers::Tag.new(params[:name])
  end
end

app/controllers/tags_controller.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.
require File.join(Rails.root, 'app', 'models', 'acts_as_taggable_on', 'tag')
require File.join(Rails.root, 'lib', 'stream', 'tag')

class TagsController < ApplicationController
  skip_before_filter :which_action_and_user
  skip_before_filter :set_grammatical_gender
  before_filter :ensure_page, :only => :show

  helper_method :tag_followed?

  respond_to :html, :only => [:show]
  respond_to :json, :only => [:index]

  def index
    if params[:q] && params[:q].length > 1 && request.format.json?
      params[:q].gsub!("#", "")
      params[:limit] = !params[:limit].blank? ? params[:limit].to_i : 10
      @tags = ActsAsTaggableOn::Tag.autocomplete(params[:q]).limit(params[:limit] - 1)
      prep_tags_for_javascript

      respond_to do |format|
        format.json{
          render(:json => @tags.to_json, :status => 200)
        }
      end
    else
      respond_to do |format|
        format.json{ render :nothing => true, :status => 422 }
        format.html{ redirect_to tag_path('partytimeexcellent') }
      end
    end
  end

  def show
    @stream = Stream::Tag.new(current_user, params[:name], :max_time => max_time, :page => params[:page])

    if params[:only_posts]
      render :partial => 'shared/stream', :locals => {:posts => @stream.stream_posts}
      return
    end
  end

 def tag_followed?
   if @tag_followed.nil?
     @tag_followed = TagFollowing.joins(:tag).where(:tags => {:name => params[:name]}, :user_id => current_user.id).exists?
   end
   @tag_followed
 end

  def prep_tags_for_javascript
    @tags.map! do |obj|
        { :name => ("#"+obj.name),
          :value => ("#"+obj.name),
          :url => tag_path(obj.name)
        }
      end

      @tags << {
        :name => ('#' + params[:q]),
        :value => ("#" + params[:q]),
        :url => tag_path(params[:q].downcase)
      }
      @tags.uniq!
  end
end

app/helpers/tags_helper.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

module TagsHelper
  def tag_page_link(tag)
    tag_name = ActsAsTaggableOn::Tag.normalize(tag)
    link_to("##{tag_name}", tag_path(:name => tag_name))
  end
end

app/views/tags/_followed_tags_listings.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- if user_signed_in?
  %ul.left_nav
    %li
      %b=link_to t('streams.followed_tag.title'), tag_followings_path, :class => 'home_selector'

      %ul.sub_nav
        - if tags.size > 0
          - for tg in tags
            %li.unfollow{:id => "tag-following-#{tg.name}"}
              .unfollow_icon.hidden
                = link_to image_tag("icons/monotone_close_exit_delete.png", :height => 16, :title => t('aspects.index.unfollow_tag', :tag => tg.name)), tag_tag_followings_path(:name => tg.name, :remote => true), :confirm => t('are_you_sure'), :method => :delete, :remote => true, :id => "unfollow_" + tg.name
              = link_to "##{tg.name}", tag_path(:name => tg.name), :class => "tag_selector"
        %li
          = form_for TagFollowing.new do |tg|
            = text_field_tag :name, "", :class => "tag_input", :placeholder => t('streams.followed_tag.add_a_tag')
            = tg.submit t('streams.followed_tag.follow'), :class => "button hidden"

app/views/tags/show.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


- content_for :page_title do
  - if @stream.tag_name
    = @stream.display_tag_name
  - else
    = t('.whatup', :pod => @pod_url)

- content_for :head do
  = include_javascripts :home
  :javascript
    $(document).ready(function(){
      // Change the text and color of the "follow this tag" button on hover.
      $(".button.tag_following").hover(function(){
        $this = $(this);
        $this.removeClass("in_aspects");
        $this.val("#{t('.stop_following', :tag => @stream.tag_name)}");
      },
      function(){
        $this = $(this);
        $this.addClass("in_aspects");
        $this.val("#{t('.following', :tag => @stream.tag_name)}");
      });
    });
    $(".people_stream .pagination a").live("click", function() {
      $.getScript(this.href);
      return false;
    });


- content_for :body_class do
  = "tags_show"

.span-6.tags_people
  %h3
    = t('people', :count => @stream.tagged_people_count)

  .side_stream.stream
    = render :partial => 'people/index', :locals => {:people => @stream.tagged_people}

  %br

  .section
    = render "tags/followed_tags_listings"

.span-15.last
  .stream_container
    #author_info
      - if user_signed_in?
        .right
          - unless tag_followed?
            = button_to t('.follow', :tag => @stream.tag_name), tag_tag_followings_path(:name => @stream.tag_name), :method => :post,   :class => 'button take_action'
          - else
            = button_to t('.following', :tag => @stream.tag_name), tag_tag_followings_path(:name => @stream.tag_name), :method => :delete,   :class => 'button red_on_hover tag_following in_aspects take_action'
      %h2
        = @stream.display_tag_name
        %small
          = t('.followed_by')
          = t('people', :count => @stream.tag_follow_count)

    - if current_user
      = render 'shared/publisher', :selected_aspects => @stream.aspect_ids, :aspect_ids => @stream.aspect_ids, :for_all_aspects => true, :aspect => @stream.aspect

    %hr

    #main_stream.stream
      - if @stream.stream_posts.length > 0
        = render 'shared/stream', :posts => @stream.stream_posts
        #pagination
          =link_to(t('more'), next_page_path, :class => 'paginate')
      - else
        = t('.nobody_talking', :tag => @stream.display_tag_name)

app/views/tags/show.mobile.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

%h1
  = @stream.display_tag_name

#main_stream.stream
  = render 'shared/stream', :posts => @stream.stream_posts
  -if @stream.stream_posts.length > 0
    #pagination
      %a.more-link.paginate{:href => next_page_path}
        %h1
          = t("more")

app/views/tags/update.js.erb
var tagName = "<%= escape_javascript(@tag.name) %>"
$("#followed_tags_listing").find("#tag-following-"+tagName).slideUp(100);
Diaspora.page.flashMessages.render({success: true, notice: Diaspora.I18n.t("tags.wasnt_that_interesting", {tagName: tagName})});