config/routes.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

Diaspora::Application.routes.draw do


  # Posting and Reading

  resources :reshares

  resources :aspects do
    put :toggle_contact_visibility
  end

  resources :status_messages, :only => [:new, :create]

  resources :posts, :only => [:show, :destroy] do
    resources :likes, :only => [:create, :destroy, :index]
    resources :comments, :only => [:new, :create, :destroy, :index]
  end
  get 'p/:id' => 'posts#show', :as => 'short_post'
  get 'public_stream' => 'posts#index', :as => 'public_stream'
  # roll up likes into a nested resource above
  resources :comments, :only => [:create, :destroy] do
    resources :likes, :only => [:create, :destroy, :index]
  end


  get 'bookmarklet' => 'status_messages#bookmarklet'

  resources :photos, :except => [:index] do
    put :make_profile_photo
  end

  # ActivityStreams routes
  scope "/activity_streams", :module => "activity_streams", :as => "activity_streams" do
    resources :photos, :controller => "photos", :only => [:create]
  end

  resources :conversations do
    resources :messages, :only => [:create, :show]
    delete 'visibility' => 'conversation_visibilities#destroy'
  end

  resources :notifications, :only => [:index, :update] do
    get :read_all, :on => :collection
  end

  resources :tags, :only => [:index]
  scope "tags/:name" do
    post   "tag_followings" => "tag_followings#create", :as => 'tag_tag_followings'
    delete "tag_followings" => "tag_followings#destroy"
  end

  post   "multiple_tag_followings" => "tag_followings#create_multiple", :as => 'multiple_tag_followings'

  get "tag_followings" => "tag_followings#index", :as => 'tag_followings'
  resources :mentions, :only => [:index]
  resources "tag_followings", :only => [:create]

  get 'comment_stream' => 'comment_stream#index', :as => 'comment_stream'

  get 'like_stream' => 'like_stream#index', :as => 'like_stream'

  get 'tags/:name' => 'tags#show', :as => 'tag'

  resources :apps, :only => [:show]

  #Cubbies info page
  resource :token, :only => :show


  # Users and people

  resource :user, :only => [:edit, :update, :destroy], :shallow => true do
    get :getting_started_completed
    get :export
    get :export_photos
  end

  controller :users do
    get 'public/:username'          => :public,           :as => 'users_public'
    match 'getting_started'         => :getting_started,  :as => 'getting_started'
    match 'privacy'                 => :privacy_settings, :as => 'privacy_settings'
    get 'getting_started_completed' => :getting_started_completed
    get 'confirm_email/:token'      => :confirm_email,    :as => 'confirm_email'
  end

  # This is a hack to overide a route created by devise.
  # I couldn't find anything in devise to skip that route, see Bug #961
  match 'users/edit' => redirect('/user/edit')

  devise_for :users, :controllers => {:registrations => "registrations",
                                      :password      => "devise/passwords",
                                      :sessions      => "sessions",
                                      :invitations   => "invitations"} do
    get 'invitations/resend/:id' => 'invitations#resend', :as => 'invitation_resend'
    get 'invitations/email' => 'invitations#email', :as => 'invite_email'
  end

  get 'login' => redirect('/users/sign_in')

  scope 'admins', :controller => :admins do
    match :user_search
    get   :admin_inviter
    get   :weekly_user_stats
    get   :correlations
    get   :stats, :as => 'pod_stats'
  end

  resource :profile, :only => [:edit, :update]

  resources :contacts,           :except => [:update, :create] do
    get :sharing, :on => :collection
  end
  resources :aspect_memberships, :only  => [:destroy, :create, :update]
  resources :share_visibilities,  :only => [:update]
  resources :blocks, :only => [:create, :destroy]

  get 'spotlight' => 'community_spotlight#index', :as => 'spotlight'

  get 'community_spotlight' => "contacts#spotlight", :as => 'community_spotlight'

  get 'stream' => "multis#index", :as => 'multi'

  resources :people, :except => [:edit, :update] do
    resources :status_messages
    resources :photos
    get  :contacts
    get "aspect_membership_button" => :aspect_membership_dropdown, :as => "aspect_membership_button"
    collection do
      post 'by_handle' => :retrieve_remote, :as => 'person_by_handle'
      get :tag_index
    end
  end
  get '/u/:username' => 'people#show', :as => 'user_profile'
  get '/u/:username/profile_photo' => 'users#user_photo'
  # Federation

  controller :publics do
    get 'webfinger'             => :webfinger
    get 'hcard/users/:guid'     => :hcard
    get '.well-known/host-meta' => :host_meta
    post 'receive/users/:guid'  => :receive
    post 'receive/public'       => :receive_public
    get 'hub'                   => :hub
  end



  # External

  resources :authorizations, :only => [:index, :destroy]
  scope "/oauth", :controller => :authorizations, :as => "oauth" do
    get "authorize" => :new
    post "authorize" => :create
    post :token
  end

  resources :services, :only => [:index, :destroy]
  controller :services do
    scope "/auth", :as => "auth" do
      match ':provider/callback' => :create
      match :failure
    end
    scope 'services' do
      match 'inviter/:provider' => :inviter, :as => 'service_inviter'
      match 'finder/:provider'  => :finder,  :as => 'friend_finder'
    end
  end

  scope 'api/v0', :controller => :apis do
    get :me
  end

  namespace :api do
    namespace :v0 do
      get "/users/:username" => 'users#show', :as => 'user'
      get "/tags/:name" => 'tags#show', :as => 'tag'
    end
  end


  # Mobile site

  get 'mobile/toggle', :to => 'home#toggle_mobile', :as => 'toggle_mobile'

  #Protocol Url
  get 'protocol' => redirect("https://github.com/diaspora/diaspora/wiki/Diaspora%27s-federation-protocol")

  # Resque web
  if AppConfig[:mount_resque_web]
    mount Resque::Server.new, :at => '/resque-jobs', :as => "resque_web"
  end

  # Logout Page (go mobile)
  get 'logged_out' => 'users#logged_out', :as => 'logged_out'

  # Startpage
  root :to => 'home#show'
end

app/models/aspect.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class Aspect < ActiveRecord::Base
  belongs_to :user

  has_many :aspect_memberships, :dependent => :destroy
  has_many :contacts, :through => :aspect_memberships

  has_many :aspect_visibilities
  has_many :posts, :through => :aspect_visibilities, :source => :shareable, :source_type => 'Post'
  has_many :photos, :through => :aspect_visibilities, :source => :shareable, :source_type => 'Photo'
  
  validates :name, :presence => true, :length => { :maximum => 20 }

  validates_uniqueness_of :name, :scope => :user_id, :case_sensitive => false

  attr_accessible :name, :contacts_visible, :order_id

  before_validation do
    name.strip!
  end

  def to_s
    name
  end

  def << (shareable)
    case shareable
      when Post
        self.posts << shareable
      when Photo
        self.photos << shareable
      else
        raise "Unknown shareable type '#{shareable.class.base_class.to_s}'"
    end
  end

end

app/controllers/aspects_controller.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

require File.join(Rails.root, "lib", 'stream', "aspect")

class AspectsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :save_sort_order, :only => :index
  before_filter :save_selected_aspects, :only => :index
  before_filter :ensure_page, :only => :index

  respond_to :html, :js
  respond_to :json, :only => [:show, :create]

  def index
    aspect_ids = (session[:a_ids] ? session[:a_ids] : [])
    @stream = Stream::Aspect.new(current_user, aspect_ids,
                               :order => sort_order,
                               :max_time => params[:max_time].to_i)

    if params[:only_posts]
      render :partial => 'shared/stream', :locals => {:posts => @stream.stream_posts}
    end
  end

  def create
    @aspect = current_user.aspects.create(params[:aspect])

    if @aspect.valid?
      flash[:notice] = I18n.t('aspects.create.success', :name => @aspect.name)
      if current_user.getting_started
        redirect_to :back
      elsif request.env['HTTP_REFERER'].include?("contacts")
        redirect_to :back
      elsif params[:aspect][:person_id].present?
        @person = Person.where(:id => params[:aspect][:person_id]).first

        if @contact = current_user.contact_for(@person)
          @contact.aspects << @aspect
        else
          @contact = current_user.share_with(@person, @aspect)
        end
      else
        redirect_to contacts_path(:a_id => @aspect.id)
      end
    else
      respond_to do |format|
        format.js { render :text => I18n.t('aspects.create.failure'), :status => 422 }
        format.html do
          flash[:error] = I18n.t('aspects.create.failure')
          redirect_to :back
        end
      end
    end
  end

  def new
    @aspect = Aspect.new
    @person_id = params[:person_id]
    @remote = params[:remote] == "true"
    respond_to do |format|
      format.html { render :layout => false }
    end
  end

  def destroy
    @aspect = current_user.aspects.where(:id => params[:id]).first

    begin
      @aspect.destroy
      flash[:notice] = I18n.t 'aspects.destroy.success', :name => @aspect.name
    rescue ActiveRecord::StatementInvalid => e
      flash[:error] = I18n.t 'aspects.destroy.failure', :name => @aspect.name
    end
    if request.referer.include?('contacts')
      redirect_to contacts_path
    else
      redirect_to aspects_path
    end
  end

  def show
    if @aspect = current_user.aspects.where(:id => params[:id]).first
      redirect_to aspects_path('a_ids[]' => @aspect.id)
    else
      redirect_to aspects_path
    end
  end

  def edit
    @aspect = current_user.aspects.where(:id => params[:id]).includes(:contacts => {:person => :profile}).first

    @contacts_in_aspect = @aspect.contacts.includes(:aspect_memberships, :person => :profile).all.sort! { |x, y| x.person.name <=> y.person.name }
    c = Contact.arel_table
    if @contacts_in_aspect.empty?
      @contacts_not_in_aspect = current_user.contacts.includes(:aspect_memberships, :person => :profile).all.sort! { |x, y| x.person.name <=> y.person.name }
    else
      @contacts_not_in_aspect = current_user.contacts.where(c[:id].not_in(@contacts_in_aspect.map(&:id))).includes(:aspect_memberships, :person => :profile).all.sort! { |x, y| x.person.name <=> y.person.name }
    end

    @contacts = @contacts_in_aspect + @contacts_not_in_aspect

    unless @aspect
      render :file => "#{Rails.root}/public/404.html", :layout => false, :status => 404
    else
      @aspect_ids = [@aspect.id]
      @aspect_contacts_count = @aspect.contacts.size
      render :layout => false
    end
  end

  def update
    @aspect = current_user.aspects.where(:id => params[:id]).first

    if @aspect.update_attributes!(params[:aspect])
      flash[:notice] = I18n.t 'aspects.update.success', :name => @aspect.name
    else
      flash[:error] = I18n.t 'aspects.update.failure', :name => @aspect.name
    end
    render :json => { :name => @aspect.name }
  end

  def toggle_contact_visibility
    @aspect = current_user.aspects.where(:id => params[:aspect_id]).first

    if @aspect.contacts_visible?
      @aspect.contacts_visible = false
    else
      @aspect.contacts_visible = true
    end
    @aspect.save
  end

  def ensure_page
    params[:max_time] ||= Time.now + 1
  end

  private

  def save_selected_aspects
    if params[:a_ids].present?
      session[:a_ids] = params[:a_ids]
    end
  end
end

app/helpers/aspects_helper.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

module AspectsHelper
  def remove_link(aspect)
    if aspect.contacts.size == 0
      link_to I18n.t('aspects.helper.remove'), aspect, :method => :delete, :confirm => I18n.t('aspects.helper.are_you_sure')
    else
      "<span class='grey' title=#{I18n.t('aspects.helper.aspect_not_empty')}>#{I18n.t('aspects.helper.remove')}</span>"
    end
  end

  def add_to_aspect_button(aspect_id, person_id)
    link_to image_tag('icons/monotone_plus_add_round.png'),
      {:controller => 'aspect_memberships',
        :action => 'create',
        :aspect_id => aspect_id,
        :person_id => person_id},
      :remote => true,
      :method => 'post',
      :class => 'add button',
      'data-aspect_id' => aspect_id,
      'data-person_id' => person_id
  end

  def remove_from_aspect_button(aspect_id, person_id)
    link_to image_tag('icons/monotone_check_yes.png'),
      {:controller => "aspect_memberships",
        :action => 'destroy',
        :id => 42,
        :aspect_id => aspect_id,
        :person_id => person_id},
      :remote => true,
      :method => 'delete',
      :class => 'added button',
      'data-aspect_id' => aspect_id,
      'data-person_id' => person_id
  end

  def aspect_membership_button(aspect, contact, person)
    return if person && person.closed_account?
    
    if contact.nil? || !contact.aspect_memberships.detect{ |am| am.aspect_id == aspect.id}
      add_to_aspect_button(aspect.id, person.id)
    else
      remove_from_aspect_button(aspect.id, person.id)
    end
  end
end

app/views/aspects/_aspect_contacts.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- content_for :head do
  =javascript_include_tag 'aspect-contacts'
  :javascript
    EditPane.setTranslations({
      doneEditing: "#{t('.done_editing')}",
      editAspect:"#{t('aspects.show.edit_aspect')}"
    });

  - if aspect.contacts.count == 0
    :javascript
      $(document).ready(function(){
        EditPane.fadeIn();
      });

#left_pane
  .section.contact_pictures
    - for contact in contacts
      = person_image_link(contact[:person])

    %br
    %br
    %br
    .section
      %h3= t('shared.invitations.invites')
      = render "shared/invitations"

app/views/aspects/_aspect_list_item.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

%li{:data=>{:guid=>aspect.id}}
  %span.name
    = link_to aspect.name, aspect
  .right
    = aspect_membership_button(aspect, contact, person)

app/views/aspects/_aspect_listings.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

%ul#aspect_nav.left_nav
  %li.all_aspects
    .root_element= link_to t('aspects.index.your_aspects'), aspects_path

    %ul.sub_nav
      - if defined?(stream)
        %a.toggle_selector{:href => '#'}
          = stream.for_all_aspects? ? t('.deselect_all') : t('.select_all')
      - for aspect in all_aspects
        %li{:data => {:aspect_id => aspect.id}, :class => ("active" if defined?(stream) && stream.aspect_ids.include?(aspect.id))}
          .edit
            = link_to image_tag("icons/pencil.png", :title => t('.edit_aspect', :name => aspect.name)), edit_aspect_path(aspect), :rel => "facebox"
          %a.aspect_selector{:href => aspects_path("a_ids[]" => aspect.id), :class => "name", 'data-guid' => aspect.id}
            = aspect

      %li
        = link_to t('.add_an_aspect'), new_aspect_path, :class => "new_aspect", :rel => "facebox"

app/views/aspects/_aspect_stream.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

#aspect_stream_header
  #sort_by
    = t('streams.recently')
    %span.controls
      = link_to_if(session[:sort_order] == 'created_at', t('streams.commented_on'), stream.link(:sort_order => 'updated_at'))
      ·
      = link_to_if(session[:sort_order] == 'updated_at', t('streams.posted'), stream.link(:sort_order => 'created_at' ))

  %h3
    = stream.title

= render 'shared/publisher', :selected_aspects => stream.aspects, :aspect_ids => stream.aspect_ids, :for_all_aspects => stream.for_all_aspects?, :aspect => stream.aspect
= render 'aspects/no_posts_message'

#gs-shim{:title => popover_with_close_html("3. #{t('.stay_updated')}"), 'data-content' => t('.stay_updated_explanation')}

#main_stream.stream{:data => {:guids => stream.aspect_ids.join(','), :time_for_scroll => time_for_scroll(stream.ajax_stream?, stream)}}
  - if !stream.ajax_stream? && stream.stream_posts.length > 0
    = render 'shared/stream', :posts => stream.stream_posts
  #pagination
    =link_to(t('more'), next_page_path(:ajax_stream => stream.ajax_stream?), :class => 'paginate')

- if current_user.contacts.size < 2
  = render 'aspects/no_contacts_message'

app/views/aspects/_no_contacts_message.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

#no_contacts.empty_message
  = t('.you_should_add_some_more_contacts')
  %br
  %br
  = t('.try_adding_some_more_contacts')
  != t('.or_spotlight', :link => link_to(t(".community_spotlight") , community_spotlight_path))

app/views/aspects/_no_posts_message.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

#no_posts.hidden.empty_message
  = t('.start_talking')

app/views/aspects/_selected_contacts.html.haml
#selected_aspect_contacts.section
  .title.no_icon
    %h5
      = @stream.contacts_title

  .content
    - if @stream.people.size > 0
      - for person in @stream.people.sample(15)
        = person_image_link(person)
      = link_to @stream.contacts_link_title, @stream.contacts_link, :id => "view_all_contacts_link"
    - else
      = t('.no_contacts')
      = link_to t('.manage_your_aspects'), contacts_link

app/views/aspects/create.js.erb
//   Copyright (c) 2010-2011, Diaspora Inc.  This file is
//   licensed under the Affero General Public License version 3 or later.  See
//   the COPYRIGHT file.

var dropdown = $("ul.dropdown_list[data-person_id=<%= @person.id %>]")
$('.newItem', dropdown).before("<%= escape_javascript( aspect_dropdown_list_item(@aspect, @contact.aspects.include?(@aspect))) %>");

ContactEdit.updateNumber(dropdown, "<%= @person.id %>", <%= @contact.aspects.size %>);
$.facebox.close();
$('#profile .dropdown').toggleClass("active");

app/views/aspects/index.html.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


- content_for :head do
  = include_javascripts :home

- if current_user.getting_started?
  #welcome-to-diaspora
    .container{:style => "position: relative;"}
      .right
        = link_to image_tag('close_label.png'), getting_started_completed_path, :id => "gs-skip-x"
      .span-23
        %h1
          = t('.welcome_to_diaspora', :name => current_user.first_name)
        %h3
          = t('.introduce_yourself')
  %br
  %br
  %br
  %br
  %br

.span-5.leftNavBar
  #home_user_badge
    = owner_image_link
    %h4
      = link_to current_user.first_name, local_or_remote_person_path(current_user.person)

  .section
    %ul.left_nav
      %li
        %b
          = link_to t("streams.multi.title"), multi_path, :class => 'home_selector'

  .section
    = render 'aspects/aspect_listings', :stream => @stream

  .section
    %ul.left_nav
      %li
        %b
          = link_to t('streams.mentions.title'), mentions_path, :class => 'home_selector'

  .section
    %ul.left_nav
      %li
        %b
          = link_to t('streams.comment_stream.title'), comment_stream_path, :class => 'home_selector'

  .section
    %ul.left_nav
      %li
        %b
          = link_to t('streams.like_stream.title'), like_stream_path, :class => 'home_selector'

  .section#followed_tags_listing
    = render 'tags/followed_tags_listings'

.span-13.append-1
  #aspect_stream_container.stream_container
    = render 'aspects/aspect_stream', :stream => @stream

.span-5.rightBar.last
  = render 'aspects/selected_contacts', :stream => @stream

  = render 'shared/right_sections'

app/views/aspects/index.js.erb
$('#aspect_stream_container').html("<%= escape_javascript(render('aspects/aspect_stream', :stream => @stream)) %>");
$('#selected_aspect_contacts').html("<%= escape_javascript(render('aspects/selected_contacts', :people => @stream.people.sample(20), :count => @stream.people.size)) %>");
$('#aspect_stream_container a[rel*=facebox]').facebox();

app/views/aspects/index.mobile.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

%h2{:style => "padding:0 10px;display:none;"}
  - if @stream.for_all_aspects?
    = t('all_aspects')
  - else
    = @stream.aspect

#main_stream.stream
  = render 'shared/stream', :posts => @stream.stream_posts
  -if @stream.stream_posts.length > 0
    #pagination
      %a.more-link.paginate{:href => next_page_path}
        %h1
          = t("more")

app/views/aspects/new.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.span-12.last
  #facebox_header
    %h3
      = t('contacts.index.add_a_new_aspect')

  = form_for(Aspect.new, :remote => @remote) do |aspect|
    = aspect.error_messages
    - if @person_id
      = aspect.hidden_field :person_id, :value => @person_id
    %p
      = aspect.label :name , t('.name')
      = aspect.text_field :name, :maxlength => 20

    %p.checkbox_select
      = aspect.label :contacts_visible, t('aspects.edit.make_aspect_list_visible')
      = aspect.check_box :contacts_visible, :default => true

    %br

    .bottom_submit_section
      = submit_tag t('cancel'), :class => 'button', :type => :reset, :rel => "close"
      = aspect.submit t('.create'), :class => 'button creation'

app/views/aspects/toggle_contact_visibility.js.erb
$(document).ready(function() {

  var padlockImg = $("#contact_visibility_padlock");

  if(padlockImg.hasClass('open')) {
    padlockImg.attr('src', 'images/icons/padlock-closed.png');
    padlockImg.attr('title', "<%= t('aspects.edit.aspect_list_is_not_visible') %>");
  } else {
    padlockImg.attr('src', 'images/icons/padlock-open.png');
    padlockImg.attr('title', "<%= t('aspects.edit..aspect_list_is_visible') %>");
  }
  padlockImg.toggleClass('open');

});

app/views/aspects/update.js.erb
$(document).ready(function() {
  var newName = "<%= @aspect.name %>"
  $("#aspect_name").val( newName );
  $("*[data-guid='<%= @aspect.id %>']").find('.name').html( newName );
});